financial/urls.py
from django.urls import path
import financial.views

urlpatterns = [
    path(
        'transactions/categories/<category_id>/delete/', financial.views.delete_transactioncategory,
        {}, 'delete_transactioncategory'),
    path(
        'transactions/categories/<category_id>/edit/', financial.views.edit_transactioncategory,
        {}, 'edit_transactioncategory'),
    path('transactions/categories/add/', financial.views.add_transactioncategory, {}, 'add_transactioncategory'),
    path('transactions/categories/', financial.views.transactioncategories, {}, 'transactioncategories'),

    path(
        'transactions/<transaction_id>/delete/', financial.views.delete_transaction,
        {}, 'delete_transaction'),
    path('transactions/<transaction_id>/edit/', financial.views.edit_transaction, {}, 'edit_transaction'),
    path('transactions/add/', financial.views.add_transaction, {}, 'add_transaction'),
    path('transactions/', financial.views.transactions, {}, 'transactions'),
    path('pdf/', financial.views.generate_pdf, {}, 'generate_pdf_financial'),
    path('summary/', financial.views.monthly_summary, {}, 'monthly_summary'),
    path('confrontation/', financial.views.confrontation, {}, 'confrontation'),
]

sgc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.views import logout_then_login
from django.conf import settings
import sgc.views
from django.conf.urls.static import static


urlpatterns = i18n_patterns(
    path('login/', sgc.views.login, {}, 'login'),
    path('logout/', logout_then_login, {'login_url': '/login/'}, 'logout'),
    path('congregations/', include('congregations.urls')),
    path('meetings/', include('meetings.urls')),
    path('users/', include('users.urls')),
    path('financial/', include('financial.urls')),
    path('preaching/', include('preaching.urls')),
    path('board/', include('board.urls')),
    path('', sgc.views.home, {}, 'home')
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.ADMIN_ENABLED:
    urlpatterns += i18n_patterns(
        path('admin/', admin.site.urls)
    )

financial/models.py
from djongo import models
from djongo.models import ObjectIdField
from django.db.models import DecimalField
from django.utils.translation import gettext_lazy as _
from congregations.models import Congregation
from users.models import User
TRANSACTION_CODE = [
    ('C', _("Congregation")),
    ('CE', _("Congregation (Electronic)")),
    ('O', _("World Wide Work")),
    ('D', _("Account Deposit")),
    ('G', _("Expense")),
    ('F', _("Construction of the Subsidiary")),
    ('J', _("Interest")),
    ('OE', _("Specific objective")),
    ('GP', _("Expense paid by Bethel")),
]
TRANSACTION_TYPE = [
    ('R', _("Receips")),
    ('C', _("Checking Account")),
    ('O', _("Other"))
]
TRANSACTION_DIRECTION = [
    ('I', _("In")),
    ('O', _("Out"))
]


class TransactionCategory(models.Model):
    _id = ObjectIdField()
    name = models.CharField(max_length=100, verbose_name=_("Name"))
    congregation = models.ForeignKey(
        Congregation, on_delete=models.CASCADE, verbose_name=_("Congregation"))
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, verbose_name=_("User"))

    objects = models.DjongoManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Transaction Category")
        verbose_name_plural = _("Transaction Categories")


class SubTransaction(models.Model):
    date = models.DateField(verbose_name=_("Date"), blank=True, null=True)
    description = models.TextField(
        verbose_name=_("Description"), help_text=_("Leave blank for a transaction on the same line as the main one"),
        blank=True)
    tc = models.CharField(max_length=2, verbose_name=_(
        "Transaction Code"), choices=TRANSACTION_CODE, blank=True)
    tt = models.CharField(max_length=1, verbose_name=_(
        "Transaction Type"), choices=TRANSACTION_TYPE)
    td = models.CharField(max_length=2, verbose_name=_(
        "Transaction Direction"), choices=TRANSACTION_DIRECTION)
    value = models.FloatField(verbose_name=_("Value"), default=0)
    category = models.ForeignKey(
        TransactionCategory, on_delete=models.PROTECT, verbose_name=_("Category"), null=True, blank=True)


class Transaction(models.Model):
    _id = ObjectIdField()
    date = models.DateField(verbose_name=_("Date"), blank=True)
    description = models.TextField(verbose_name=_("Description"), blank=True)
    tc = models.CharField(max_length=2, verbose_name=_(
        "Transaction Code"), choices=TRANSACTION_CODE, blank=True)
    tt = models.CharField(max_length=1, verbose_name=_(
        "Transaction Type"), choices=TRANSACTION_TYPE)
    td = models.CharField(max_length=2, verbose_name=_(
        "Transaction Direction"), choices=TRANSACTION_DIRECTION)
    value = models.FloatField(verbose_name=_("Value"), default=0)
    note = models.TextField(verbose_name=_("Note"), blank=True)
    congregation = models.ForeignKey(
        Congregation, on_delete=models.CASCADE, verbose_name=_("Congregation"))
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, verbose_name=_("User"))
    category = models.ForeignKey(
        TransactionCategory, on_delete=models.PROTECT, verbose_name=_("Category"), null=True, blank=True)
    hide_from_sheet = models.BooleanField(verbose_name=_(
        "Hide from Transaction Sheet"), default=False)
    sub_transactions = models.ArrayModelField(model_container=SubTransaction)

    objects = models.DjongoManager()

    def __str__(self):
        return '({}) - {}'.format(self.date, self.description)

    class Meta:
        verbose_name = _("Transaction")
        verbose_name_plural = _("Transactions")
        ordering = ['date', ]


class TransactionContent(models.Model):
    tc = models.CharField(max_length=2, verbose_name=_(
        "Transaction Code"), choices=TRANSACTION_CODE, blank=True)
    count = models.IntegerField(verbose_name=_("Count"))
    value = models.DecimalMongoField(verbose_name=_(
        "Value"), default=0, decimal_places=2, max_digits=10)


class MonthlySummary(models.Model):
    _id = ObjectIdField()
    date = models.DateField(verbose_name=_("Date"))
    carried_balance = DecimalField(verbose_name=_(
        "Carried Balance"), default=0, decimal_places=2, max_digits=10)
    final_balance = DecimalField(verbose_name=_(
        "Final Balance"), default=0, decimal_places=2, max_digits=10)
    transactions = models.ArrayModelField(model_container=TransactionContent)
    congregation = models.ForeignKey(
        Congregation, on_delete=models.CASCADE, verbose_name=_("Congregation"))

    objects = models.DjongoManager()

    class Meta:
        verbose_name = _("Monthly Summary")
        verbose_name_plural = _("Monthly Summaries")
        ordering = ['-date', ]

financial/views.py
import datetime
import calendar
from collections import Counter
from dateutil.relativedelta import relativedelta
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.utils.translation import gettext_lazy as _
from django.contrib import messages
from django_tables2.config import RequestConfig
from django_tables2 import Column
from financial.models import Transaction, TransactionCategory, MonthlySummary, SubTransaction
from financial.tables import TableTransactions, TableTransactionCategories, TableMonthlySummary, TableConfrontation
from financial.forms import (
    FormTransaction, FormSearchTransaction, FormGeneratePDF, FormSearchTransactionCategory, FormTransactionCategory,
    FormMonthlySummary, FormUnverifiedChecks, FormOffTransaction)
from financial.helpers import TransactionSheetPdf, MonthlyReportPdf
from sgc.helpers import redirect_with_next
from bson.objectid import ObjectId


@login_required
def transactions(request):
    form = FormSearchTransaction(request.GET)
    filter_data = {}
    if form.is_valid():
        data = form.cleaned_data
        if 'start_date' in data and data['start_date']:
            filter_data['date__gte'] = data['start_date']
        else:
            filter_data['date__gte'] = datetime.datetime.now().replace(day=1)
        if 'end_date' in data and data['end_date']:
            filter_data['date__lte'] = data['end_date']
        if 'tc' in data and data['tc']:
            filter_data['tc'] = data['tc']
        if 'tt' in data and data['tt']:
            filter_data['tt'] = data['tt']
        if 'td' in data and data['td']:
            filter_data['td'] = data['td']
    filter_data['congregation_id'] = request.user.congregation_id
    summary = {}
    data = Transaction.objects.filter(**filter_data).select_related('category')
    new_data = []
    for t in data:
        new_data.append({
            'pk': t.pk,
            'date': t.date,
            'description': t.description,
            'tc': t.get_tc_display(),
            'td': t.get_td_display(),
            'tt': t.get_tt_display(),
            'category': str(t.category) if t.category else "",
            'value': t.value
        })
        if t.tc:
            if t.tc not in summary:
                summary[t.tc] = {'name': t.get_tc_display(), 'value': 0}
            summary[t.tc]['value'] += t.value
        if t.sub_transactions:
            for s in t.sub_transactions:
                new_data.append({
                    'date': s.date,
                    'description': s.description,
                    'tc': s.get_tc_display(),
                    'td': s.get_td_display(),
                    'tt': s.get_tt_display(),
                    'category': str(s.category) if s.category else "",
                    'value': s.value
                })
                if s.tc:
                    if s.tc not in summary:
                        summary[s.tc] = {
                            'name': s.get_tc_display(), 'value': 0}
                    summary[s.tc]['value'] += s.value
    table = TableTransactions(new_data)
    table.paginate(page=request.GET.get('page', 1), per_page=25)
    RequestConfig(request).configure(table)
    return render(request, 'transactions.html', {
        'request': request, 'table': table, 'form': form,
        'page_group': 'financial', 'page_title': _("Transactions"),
        'next': request.GET.copy().urlencode(),
        'summary': summary
    })


@login_required
def add_transaction(request):
    if request.method == 'POST':
        transactions = []
        tops = {}
        last_date = None
        for i, date in enumerate(request.POST.getlist('date')):
            category = request.POST.getlist('category')[i]
            top_id = request.POST.getlist('top_id')[i]
            if not date and top_id and last_date:
                date = last_date
            last_date = date
            if request.LANGUAGE_CODE == 'en':
                date = datetime.datetime.strptime(date, '%Y-%m-%d')
            else:
                date = datetime.datetime.strptime(date, '%d/%m/%Y')
            transactions.append({
                'date': date,
                'description': request.POST.getlist('description')[i],
                'tc': request.POST.getlist('tc')[i],
                'td': request.POST.getlist('td')[i],
                'tt': request.POST.getlist('tt')[i],
                'value': float(request.POST.getlist('value')[i]),
                'category_id': category if category else None,
                'id': request.POST.getlist('id')[i],
                'top_id': request.POST.getlist('top_id')[i]
            })
        for transaction in [x for x in transactions if x['top_id']]:
            if transaction['top_id'] not in tops:
                tops[transaction['top_id']] = []
            tops[transaction['top_id']].append(SubTransaction(
                date=transaction['date'],
                description=transaction['description'],
                tc=transaction['tc'],
                td=transaction['td'],
                tt=transaction['tt'],
                value=float(transaction['value']),
                category_id=transaction['category_id']
            ))
        for transaction in [x for x in transactions if not x['top_id']]:
            if transaction['id'] in tops:
                subs = tops[transaction['id']]
                value = sum([float(x.value) for x in subs])
            else:
                subs = []
                value = transaction['value']
            Transaction(
                date=transaction['date'],
                description=transaction['description'],
                tc=transaction['tc'],
                td=transaction['td'],
                tt=transaction['tt'],
                value=float(value),
                category_id=transaction['category_id'],
                sub_transactions=subs,
                congregation_id=request.user.congregation_id,
                user=request.user
            ).save()

        messages.success(request, _("Transaction added successfully"))
        return redirect_with_next(request, 'transactions')
    else:
        form = FormTransaction()
    return render(request, 'add_transactions.html', {
        'request': request, 'form': form, 'page_group': 'financial', 'page_title': _("Add Transactions")
    })


@login_required
def edit_transaction(request, transaction_id):
    transaction = get_object_or_404(Transaction, pk=ObjectId(transaction_id))
    if request.method == 'POST':

        transaction.sub_transactions = []
        last_date = None
        print(request.POST)
        for i, date in enumerate(request.POST.getlist('date')):
            category = request.POST.getlist('category')[i]
            if not date and last_date:
                date = last_date
            last_date = date
            if request.LANGUAGE_CODE == 'en':
                date = datetime.datetime.strptime(date, '%Y-%m-%d')
            else:
                date = datetime.datetime.strptime(date, '%d/%m/%Y')
            item = {
                'date': date,
                'description': request.POST.getlist('description')[i],
                'tc': request.POST.getlist('tc')[i],
                'td': request.POST.getlist('td')[i],
                'tt': request.POST.getlist('tt')[i],
                'value': float(request.POST.getlist('value')[i]),
                'category_id': category if category else None
            }
            if i == 0:
                transaction.date = item['date']
                transaction.description = item['description']
                transaction.tc = item['tc']
                transaction.td = item['td']
                transaction.tt = item['tt']
                transaction.value = float(item['value'])
                transaction.category_id = item['category_id']
            else:
                transaction.sub_transactions.append(SubTransaction(**item))
        if transaction.sub_transactions:
            transaction.value = sum([float(x.value)
                                    for x in transaction.sub_transactions])
        transaction.save()
        messages.success(request, _("Transaction edited successfully"))
        return redirect_with_next(request, 'transactions')

    form = FormTransaction(instance=transaction)
    new_form = FormTransaction()
    sub_transactions = []
    for s in transaction.sub_transactions:
        sub_transactions.append(FormTransaction(
            instance=s))
    return render(request, 'edit_transaction.html', {
        'request': request, 'form': form, 'page_group': 'financial', 'page_title': _("Edit Transaction"),
        'transaction': transaction, 'new_form': new_form, 'sub_transactions': sub_transactions
    })


@login_required
def delete_transaction(request, transaction_id):
    transaction = get_object_or_404(Transaction, pk=ObjectId(transaction_id))
    transaction.delete()
    messages.success(request, _("Transaction deleted successfully"))
    return redirect_with_next(request, 'transactions')


@login_required
def generate_pdf(request):
    if request.method == 'POST':
        form = FormGeneratePDF(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            if data['type_pdf'] == 's26':
                checks = []
                for i, n_confirmaation in enumerate(request.POST.getlist('n_confirmation')):
                    checks.append({
                        'n_confirmation': n_confirmaation,
                        'value': request.POST.getlist('value')[i]
                    })
                data_off = {}
                formOffTransaction = FormOffTransaction(request.POST)
                if formOffTransaction.is_valid():
                    data_off = formOffTransaction.cleaned_data
                s26 = TransactionSheetPdf(

financial/templates/actions_table_transactioncategories.html
<div class="btn-group btn-group-sm" role="group">
    <button id="btnGroupVerticalDrop1" type="button" class="btn btn-sm btn-secondary dropdown-toggle btn-action" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {% trans 'Actions' %}
    </button>
    <div class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop1">
        <a class="dropdown-item action-item" href="{% url 'edit_transactioncategory' record.pk %}?{{next}}">{% trans 'Edit' %}</a>
        <a class="dropdown-item action-item" href="{% url 'delete_transactioncategory' record.pk %}?{{next}}" onclick="return confirm('{% trans "Are you sure?" %}');">{% trans 'Delete' %}</a>
    </div>
</div>

financial/templates/actions_table_transactions.html
{% if record.pk %}
<div class="btn-group btn-group-sm" role="group">
    <button id="btnGroupVerticalDrop1" type="button" class="btn btn-sm btn-secondary dropdown-toggle btn-action" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {% trans 'Actions' %}
    </button>
    <div class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop1">
        <a class="dropdown-item action-item" href="{% url 'edit_transaction' record.pk %}?{{next}}">{% trans 'Edit' %}</a>
        <a class="dropdown-item action-item" href="{% url 'delete_transaction' record.pk %}?{{next}}" onclick="return confirm('{% trans "Are you sure?" %}');">{% trans 'Delete' %}</a>
    </div>
</div>
{% endif %}

financial/templates/add_edit_transactioncategory.html
{% extends 'base.html' %}
{% block title %} - {{page_title}}{% endblock %}

{% block breadcrumb %}

<div class="page-title-box">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <h4 class="page-title">{{page_title}}</h4>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
                <li class="breadcrumb-item"><a href="{% url 'transactioncategories' %}">{% trans 'Transaction Categories' %}</a></li>
                <li class="breadcrumb-item active">{{page_title}}</li>
            </ol>

        </div>
    </div>
</div>
{% endblock %}


{% block body %}
<div class="row col-12 card card-body">

    <form id="form" action=".?{% get_next request %}" method="post" class="form-horizontal"autocomplete=off>

        {% csrf_token %}
        {% bootstrap_form form %}

        <button id="submit" class="btn btn-primary pull-right" type="submit">{% trans 'Send' %}</button>
    </form>
</div>

{% endblock %}

financial/templates/add_transactions.html
{% extends 'base.html' %}
{% block title %} - {{page_title}}{% endblock %}

{% block breadcrumb %}

<div class="page-title-box">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <h4 class="page-title">{{page_title}}</h4>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
                <li class="breadcrumb-item"><a href="{% url 'transactions' %}">{% trans 'Transactions' %}</a></li>
                <li class="breadcrumb-item active">{{page_title}}</li>
            </ol>

        </div>
    </div>
</div>

{% endblock %}


{% block body %}
<div class="row col-12 card card-body">

    <form id="form" action=".?{% get_next request %}" method="post" class="form-horizontal"autocomplete=off>

        {% csrf_token %}
        <button type="button" class="btn btn-success addItem"><span class="fa fa-plus fa-lg"></span> {% trans 'Add' %}</button>
        <div id="boxTransactions">
        </div>

        <button id="submit" class="btn btn-primary pull-right" type="submit">{% trans 'Send' %}</button>
    </form>
</div>
<div id="transactionModel" class="card border-primary card-body boxItem" style="display:none">
    <div class="row">
        <input type="hidden" name="id"/>
        <input type="hidden" name="top_id"/>
        <div class="col-lg-1">
            {% bootstrap_field form.date %}
        </div>
        <div class="col-lg-2">
            {% bootstrap_field form.description %}
        </div>
        <div class="col-lg-2">
            {% bootstrap_field form.tc %}
        </div>
        <div class="col-lg-2">
            {% bootstrap_field form.tt %}
        </div>
        <div class="col-lg-2">
            {% bootstrap_field form.td %}
        </div>
        <div class="col-lg-1">
            {% bootstrap_field form.value %}
        </div>
        <div class="col-lg-2">
            {% bootstrap_field form.category %}
        </div>
        <div class="pull-right">
            <span class="fa fa-exchange fa-lg addInlineItem"></span>
            <span class="fa fa-plus fa-lg addItemSub"></span>
            <span class="fa fa-times fa-lg removeItem"></span>
        </div>
        <div class="transactions col-lg-12 pl-5">
        </div>
    </div>
</div>
{% endblock %}

{% block extrajs %}
<script>
    function makeid(length) {
       var result           = '';
       var characters       = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
       var charactersLength = characters.length;
       for ( var i = 0; i < length; i++ ) {
          result += characters.charAt(Math.floor(Math.random() * charactersLength));
       }
       return result;
    }
    $(document).ready(function() {
        function insert_transaction(top_id, inline=false){
            var box = $('#transactionModel').clone();
            box.attr('id', '');
            box.show();
            box.find('select').selectpicker({"actionsBox": true, "liveSearch": true, "liveSearchNormalize": true});
            box.find('input[name="date"]').datetimepicker({format: 'DD/MM/YYYY'}).find('input').addClass("form-control");
            box.find('input[name="id"]').val(makeid(10));
            if(inline){
                box.find('label[for="id_date"]').parent().hide();
                box.find('label[for="id_description"]').parent().hide();
                box.find('label[for="id_tc"]').parent().hide();
                box.find('label[for="id_category"]').parent().hide();
            }
            if(top_id != null){
                box.find('input[name="top_id"]').val(top_id);
                box.find('.addItemSub').remove();
                box.find('.addInlineItem').remove();
                $('#boxTransactions').find('input[value="' + top_id + '"][name="id"]').parent().children('.transactions').append(box);
            }else{
                $('#boxTransactions').append(box);
            }
        }
        insert_transaction(null);

        $('.addItem').on('click', function(e){
            insert_transaction(null);
        });
        $('#boxTransactions').on('click', '.addItemSub', function(e){
            var top_id = $(this).parent().parent().children('input[name="id"]').val();
            insert_transaction(top_id);
        });
        $('#boxTransactions').on('click', '.addInlineItem', function(e){
            var top_id = $(this).parent().parent().children('input[name="id"]').val();
            insert_transaction(top_id, true);
        });
        $('#boxTransactions').on('click', '.removeItem', function(){
            $(this).parent().parent().parent().remove();
        });
    });
</script>
{% endblock %}

financial/templates/edit_transaction.html
{% extends 'base.html' %}
{% block title %} - {{page_title}}{% endblock %}

{% block breadcrumb %}

<div class="page-title-box">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <h4 class="page-title">{{page_title}}</h4>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
                <li class="breadcrumb-item"><a href="{% url 'transactions' %}">{% trans 'Transactions' %}</a></li>
                <li class="breadcrumb-item active">{{page_title}}</li>
            </ol>

        </div>
    </div>
</div>
{% endblock %}


{% block body %}
<div class="row col-12 card card-body">

    <form id="boxTransactions" action=".?{% get_next request %}" method="post" class="form-horizontal" autocomplete=off>

        {% csrf_token %}
        <div class="card border-primary card-body boxItem">
            <div class="row">
                <div class="col-lg-1">
                    {% bootstrap_field form.date %}
                </div>
                <div class="col-lg-2">
                    {% bootstrap_field form.description %}
                </div>
                <div class="col-lg-2">
                    {% bootstrap_field form.tc %}
                </div>
                <div class="col-lg-2">
                    {% bootstrap_field form.tt %}
                </div>
                <div class="col-lg-2">
                    {% bootstrap_field form.td %}
                </div>
                <div class="col-lg-1">
                    {% bootstrap_field form.value %}
                </div>
                <div class="col-lg-2">
                    {% bootstrap_field form.category %}
                </div>
                <div class="pull-right">
                    <span class="fa fa-exchange fa-lg addInlineItem"></span>
                    <span class="fa fa-plus fa-lg addItemSub"></span>
                    <span class="fa fa-times fa-lg removeItem"></span>
                </div>
                <div class="transactions col-lg-12 pl-5">
                    {% for s in sub_transactions %}
                        <div class="card border-primary card-body boxItem">
                            <div class="row">
                                <div class="col-lg-1">
                                    {% if not s.description %}
                                    {% bootstrap_field s.date %}
                                    {% endif %}
                                </div>
                                <div class="col-lg-2">
                                    {% if not s.description %}
                                    {% bootstrap_field s.description %}
                                    {% endif %}
                                </div>
                                <div class="col-lg-2">
                                    {% if not s.description %}
                                    {% bootstrap_field s.tc %}
                                    {% endif %}
                                </div>
                                <div class="col-lg-2">
                                    {% bootstrap_field s.tt %}
                                </div>
                                <div class="col-lg-2">
                                    {% bootstrap_field s.td %}
                                </div>
                                <div class="col-lg-1">
                                    {% bootstrap_field s.value %}
                                </div>
                                <div class="col-lg-2">
                                    {% if not s.description %}
                                    {% bootstrap_field s.category %}
                                    {% endif %}
                                </div>
                                <div class="pull-right"><span class="fa fa-times fa-lg removeItem"></span></div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <button id="submit" class="btn btn-primary pull-right" type="submit">{% trans 'Send' %}</button>
    </form>
</div>
<div id="transactionModel" class="card border-primary card-body boxItem" style="display:none">
    <div class="row">
        <div class="col-lg-1">
            {% bootstrap_field new_form.date %}
        </div>
        <div class="col-lg-2">
            {% bootstrap_field new_form.description %}
        </div>
        <div class="col-lg-2">
            {% bootstrap_field new_form.tc %}
        </div>
        <div class="col-lg-2">
            {% bootstrap_field new_form.tt %}
        </div>
        <div class="col-lg-2">
            {% bootstrap_field new_form.td %}
        </div>
        <div class="col-lg-1">
            {% bootstrap_field new_form.value %}
        </div>
        <div class="col-lg-2">
            {% bootstrap_field new_form.category %}
        </div>
        <div class="pull-right"> <span class="fa fa-times fa-lg removeItem"></span></div>

    </div>
</div>
{% endblock %}

{% block extrajs %}
<script>
    function makeid(length) {
       var result           = '';
       var characters       = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
       var charactersLength = characters.length;
       for ( var i = 0; i < length; i++ ) {
          result += characters.charAt(Math.floor(Math.random() * charactersLength));
       }
       return result;
    }
    $(document).ready(function() {
        function insert_transaction(top_id, inline=false){
            var box = $('#transactionModel').clone();
            box.attr('id', '');
            box.show();
            box.find('select').selectpicker({"actionsBox": true, "liveSearch": true, "liveSearchNormalize": true});
            box.find('input[name="date"]').datetimepicker({format: 'DD/MM/YYYY'}).find('input').addClass("form-control");
            box.find('input[name="id"]').val(makeid(10));
            if(inline){
                box.find('label[for="id_date"]').parent().hide();
                box.find('label[for="id_description"]').parent().hide();
                box.find('label[for="id_tc"]').parent().hide();
                box.find('label[for="id_category"]').parent().hide();
            }
            $('#boxTransactions').find('.transactions').append(box);
        }
        $('#boxTransactions').on('click', '.addItemSub', function(e){
            var top_id = $(this).parent().parent().children('input[name="id"]').val();
            insert_transaction(top_id);
        });
        $('#boxTransactions').on('click', '.addInlineItem', function(e){
            var top_id = $(this).parent().parent().children('input[name="id"]').val();
            insert_transaction(top_id, true);
        });
        $('#boxTransactions').on('click', '.removeItem', function(){
            $(this).parent().parent().parent().remove();
        });
    });
</script>
{% endblock %}